### ISSUE TITLE
怎么下载svg格式的icon

### ISSUE THREAD

**Issue by SwordBearFire** [ztw33/download_iconfont#1]
博主您好，

我用了您的代码确实能爬下来iconfont的图标，不知道能不能爬取svg格式的icon呢？

谢谢您～

**Comment by ztw33** [comment]
您好，非常抱歉，在暂时的代码中无法完成这个功能呢555
因为当时在我的使用场景中对图标的质量要求不是很高而且只要png就行，所以图快就基于截图做的爬取；如果要下载svg格式要在登录状态下下载，所以暂时没办法做到呢
不过过段时间等我有空可能会尝试改一改 实在不好意思啦！

**Comment by SwordBearFire** [comment]
哇，博主回复好及时，感动～

我尝试用requests包来请求iconfont的网页源码，但是得到的好像和浏览器看到的不太一样，不知道能不能用这种自动化测试脚本来把网页源码类似我们用右键的方式保存下来，然后在本地解析保存的网页再爬每个icon的svg文件。

谢谢美丽的博主小姐姐～

**Comment by ztw33** [comment]
啊我感觉他这个资源是不能直接从网页源码获取的，所以从网页html应该是没办法获取到文件的吧
感觉还是得通过脚本像人一样点击下载？
我也不太确定！网页前端这方面不是太了解，如果您有什么好的解决方案也希望告知我一下！

**Comment by SwordBearFire** [comment]
我现在有个特别人工的方法，鼠标右键把网页存到本地，能获取到每个icon的svg源码，然后在用某些包把html里面的svg源码解析出来，就是保存网页会有点累，八百多个页面，每个页面还有十几个子页面，有点难搞。
不知道博主能不能提供个联系方式，有问题想咨询。

**Comment by ztw33** [comment]
可以加我qq: 852445892

**Comment by MingtaoGuo** [comment]
大佬牛批
